language: node_js
deploy:
  provider: heroku
  api_key:
    secure: zUFhL5OV1eZMlW0aENs7z1h5dIoeun5keIAG6NjOZLzE/TC5dBCVjHEUbvnakBm+oiiSSdmD6rhOOptP9AdXh4Otzi05XJomCeKTfFqbg13yvVhG8UEex0OruQliKaRPJPax8mgZfJFpkJX0+RkSgZ1EWcBvcei4WR+1kzjPsfv5RD8cmKa5Ejh3vfF+infO3rCZZEz1UVZm+TOpdm+O/GQVNDsbEWTDCNmmGJ+7lj3psCw2uNtsBrUuD6B+j6UpTKSuqdI1t8VO/dZfOO8GWuQto41JNRVvpMZ00mgrKv6P/fPhhEoklnfikgJu1drJp+hejDuvL4pBuKNIg2x5yNDhkOCyL4rNQ5H1r6J5MBFRTObQ8MSap67EpHR8ccnHDsw61dxmbj7CnSDVsGhotNM1f8dPpYyqGgojKlRJ4LlKHyjIH30NMDmEUZlR8GPzewBiPE70n0Hh7LB3MJb1w71/i5UUy3ms5qRuDjL3L9yThhiKmWFsLo/XBDBDjrcBbr3YVNFr9W2mhasqOc/DMyP3XNLZxLzyJ8trzVMG8GsLWVVud/Cb5Hwjis9ENs1w/+B+xe/V8DAmyJDydArLbpi86gbPF+ROZdUk6M8FEL0BosbjGBlGVWCWRKgsBXh5a19936UFQeUn41SLG4raxJ7ZlRjAlJVDIMKkGUCfayw=
  app: device-library-api
